### ISSUE TITLE
Theia doesn't build and run on Mac (theia-core not build/installed?)

### ISSUE THREAD

**Issue by snorthov** [theia-ide/theia#236]
I'm doing this:

git clone https://github.com/theia-ide/theia \
&& cd theia \
&& npm install \
&& cd config/local-dependency-manager \
&& npm install \
&& cd ../../examples/browser \
&& npm run bootstrap \
&& npm run start

I get this:

... stuff deleted ...
[webpack-server]    [84] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
[webpack-server]    [85] ./src/frontend/main.ts 255 bytes {0} [built] [failed] [16 errors]
[webpack-server]    [87] multi (webpack)-dev-server/client?http://127.0.0.1:8080 webpack/hot/dev-server ./src/frontend/index.ts 52 bytes {0} [built]
[webpack-server]      + 73 hidden modules
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (9,63): error TS2307: Cannot find module 'theia-core/lib/application/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (10,33): error TS2307: Cannot find module 'theia-core/lib/messaging/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (11,33): error TS2307: Cannot find module 'theia-core/lib/navigator/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (12,40): error TS2307: Cannot find module 'theia-core/lib/filesystem/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (13,30): error TS2307: Cannot find module 'theia-core/lib/editor/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (14,41): error TS2307: Cannot find module 'theia-core/lib/languages/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (15,30): error TS2307: Cannot find module 'theia-core/lib/monaco/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (16,40): error TS2307: Cannot find module 'theia-core/lib/application/browser/clipboard/clipboard-module'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (17,35): error TS2307: Cannot find module 'theia-core/lib/application/browser/menu/menu-module'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (18,38): error TS2307: Cannot find module 'theia-core/lib/application/browser/logger-frontend-module'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (25,36): error TS2307: Cannot find module 'theia-core/lib/terminal/browser/terminal-frontend-module'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (29,36): error TS2307: Cannot find module 'theia-core/lib/java/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (33,38): error TS2307: Cannot find module 'theia-core/lib/python/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (36,35): error TS2307: Cannot find module 'theia-core/lib/cpp/browser'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] (63,17): error TS2339: Property 'start' does not exist on type '{}'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (12,87): error TS2307: Cannot find module 'theia-core/lib/application/node'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (13,40): error TS2307: Cannot find module 'theia-core/lib/filesystem/node'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (14,33): error TS2307: Cannot find module 'theia-core/lib/messaging/node'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (15,40): error TS2307: Cannot find module 'theia-core/lib/languages/node'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (16,35): error TS2307: Cannot find module 'theia-core/lib/java/node'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (17,37): error TS2307: Cannot find module 'theia-core/lib/python/node'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (18,34): error TS2307: Cannot find module 'theia-core/lib/cpp/node'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (19,35): error TS2307: Cannot find module 'theia-core/lib/terminal/node/terminal-backend-module'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (20,37): error TS2307: Cannot find module 'theia-core/lib/application/node/logger-backend-module'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (21,36): error TS2307: Cannot find module 'theia-cor
[webpack-server] [HPM] Error occurred while trying to proxy request / from 127.0.0.1:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[webpack-server] e/lib/application/node/logger-server-module'.
[webpack-server] 
[webpack-server] ERROR in /Users/snorthov/git/theia/examples/browser/src/backend/main.ts
[webpack-server] (60,13): error TS2339: Property 'start' does not exist on type '{}'.
[webpack-server] 
[webpack-server] ERROR in ./src/frontend/main.ts
[webpack-server] Module build failed: Error: Typescript emitted no output for /Users/snorthov/git/theia/examples/browser/src/frontend/main.ts.
[webpack-server]     at Object.loader (/Users/snorthov/git/theia/examples/browser/node_modules/ts-loader/dist/index.js:32:15)
[webpack-server]  @ ./src/frontend/index.ts 28:12-29
[webpack-server]  @ multi (webpack)-dev-server/client?http://127.0.0.1:8080 webpack/hot/dev-server ./src/frontend/index.ts
[webpack-server] webpack: Failed to compile.
[webpack-server] [HPM] Error occurred while trying to proxy request /favicon.ico from 127.0.0.1:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by marcdumais-work** [comment]
Hi!
Which version of nodeJS are you using? Seems that version 7.x works best, following recent changes in Theia (6.x used to work for me until recently).

**Comment by snorthov** [comment]
steves-mbp-2:git snorthov$ node --version
v6.10.1

**Comment by marcdumais-work** [comment]
I just confirmed it works for me, on v7.10.0. Can you give that a try?

**Comment by snorthov** [comment]
I will.  FYI: Node 8 doesn't work.

**Comment by snorthov** [comment]
Works in 7.10
